language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: NTZU9YsSsNLCn6ANtDz6kbITq17dmjWCj6NafnCo3O4K+HYDP28/B8TJh3BU3MwnIaS2YAnQHeHpws9W7lh9GS0L1eR9xTzlmncJ5OmvojTFNnLYHGWQ6xHeOvBd4P/4542qjiDFzGqO971/0ljWT/kVrM7V6yl5No13b1JubWNBhB3CoVP462eVtqiP2wLV7dtLiEu9OnG4kdyJe877zjbtJ4JXq7FXXa5GGyG22ij5I95Ou8FJ2gL/lSv0u5cMFfFPDkEn80OKpkxxS4Q1h21QrrD4Rd51WSPkGJOniMEAjDYFehTX0AStK/C/hGvCrihui1JQDFLZHbf1egKIH5fXaDvI5kRsLWA3sZAhdcF0VcVgRzNQiXoFwMzGO/Rm3X77N3kC3Wkb6BieWO8wY19K1a+PejnClZ57ublkQXBcn4IMUPHEli3I0wWM7W0ucyg20HJS4CYnWnnpmH/ybmHRXjK067oRsg7t2xvIbpAbQzw8KoH4Z67efBycyyvNolYX7XgNQcwdlfVCaQnyqJF3OKQKEPUMFe21V4nZRNtEIEXhE9JDy8+g/ahKREHux0dbjj5zYvrOcsEfmMtbndjXAHvZhhr8zED8O8l2ZUz3BN1xxuKE3d/GxBYw8zkH4UCH/E1HGkRDUn6EmF8fymnRiKruQQpbNYQGuyYS3Ec=
