language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: sKLCPrW50Ug00qzzjXUzO2b/yTNPVvaTG7m3ILTxlgAb74yDBkLXjv0da7VuGRvJ3+cyRJcTrBQ13BV4ptwO6AmoGk5x8Iog2C7I72s2d4dphDS9J+MS1cnCWB7OuXnJno3mcs+b8nv4UpHnd36pGMIr8t9jQvRAMuQVzh6ANo6l4gRUJmnVidMJraEOHTVjYKNw4irzAUu68V3g4N6s4aqPdINBCkuxWMzbKrI9aEIwoRo+aOPBdf0/eN9r/o8ie7NKmGRjklodKv2cWbiX750/QX2Mehhuip+yEaj+9untuQpP69JKwvXOP8kANJui1SQ5fNfdDsvblTX3fbvhOoBIPyxK5qFTf7QTsCDXu/ZsBs7L77JnOJgu4+VUrrAEhIivxKYvIrSNfTTUQ3iV5eCEhnc6pyGq3LemJjlRHnnLVX46aLrZP6eyQ2fMnO/dAL0vXixjQW1yMYS8Zg+WzMltR+MN4uz5XHvKrqFG7GO30pUcF4SQ6clMZ/jtYd6XRZ6DNCz3MbR+PNdn0FfU2pZw+i+WwGMWClOUGaHWVGIaJo21tApVoFBdH00GHGfpnuGYGqB9j+f27MYlaXtv4gseQLS3MYq6CYj1wnY7IMXU164BROKQs5dIC32ldx5XsAf6Z66dTCS8FVvqgKvDICYYqJKqthPP6+jtJoOzuzU=
