language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: lpjCKCI327wLX3cMG1h44NL7Jjq0klbqZ+twEmf0YzqLDmYIEJhT28XQ9n0RqNWsEVpuWPV6WbNY6sfmurSjC4siW9G0WIoxxKiKH2nB4IhJz4gPAzIR+jvL9dlZbwRCx506VSMYNYokwn/UtTCAwj2HoylLF6yWDxIGSr3JXoUoxrtswMO4QJR4F8Le7oJc/9sCqQgQnpZYTRJ0caiAb0yU59lS80Q6/gtQHFg4e7/kmpJYRZtsI1lsW5lB6ewPrnz7Q/zj9UwrxC+8ORUMnRgv2oGQCZ8PsbQ1DIsJlopnaAnmMg4I1+bq91tPn/k16y52pkWbepklKSlWoLFVs9txpbJqlp8/ff75avdWgVDznys/7RtP+uTuu2Cl6gepTVoxIUBUizMuH4naen4UFYB/nS2w87j0QoMyJX/wE44LLeEJW5fzn9etvg8UA4wNmvgr7wfStv12nQvcMxGcSEn8tjhjQH39xQt8vf8u7JKpAbllhjELN360tpzKUTq1iyuIExACTGSfNUfB87lU72shqcLBGpzTO8aLKeYDgCNZ4FiseAri4kd1uAWL0KpKDgwKEuQnRnk57Gu/X612i4A4flA3prhCn5IDMuaZ6Y5IAsfB1xg/6A5bt5pvbwjgINUbuJtIzUNkz/F26Uluovu8BtBxoHjQsjp2YYpLFv4=
