language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: nBsC39qORTf2uvE+sayicgolHEoztvKSPhGdzuZQmcYm/Shnr/NkN9V8fOoGq5T3DbE7jYKRflHjCtaNAn5IbrztLdRo9tSKwAgezsqv8GNxWeasCogNAmC0hp9uUYCLy7Y8Y4QI2gTI1uaEnpXZdUd26CAgFJy+FsWmsM68RsyelEgFxgQmX82PBIVr3I6mVyuKXAcBG3IXmIJUXTWkk1aQ7rbIUF5MV2H8bQwFZJlFI6oPmVUrxcuumKo1mszcAaCIlxgZ3e8D9RiI/A2Dc3pO7fUhRiiMNibzCk4c87m12q5fNqzy6VGNRvJuRFOOUBPV5ZGln+eptmngCcC3mPczflI/f8LpaYVz/SYKaJO2KvDj+WNy5N754vtTDozPYpnTtuRQC6Te0+KAdpA0mJN0out2wmHbDhqeupHWjCHajP7QzIl1G3HcFg4mHobYmMMy2eWHcWqVj5NVWm8sQvW0wAfu4QnIrNisAEKI9AXCacdafRVCeLuZbPErIbSMXjz9RF7ZKnJDTEyTu2CTxw7O0A/n0acoIHoNlWCTGZJoEuvGDAKI9pwKPsQtN3Ac6KNjMz0+t6UJC3AkdlvljRNyBnC/RsUI3T6gsHQY8aF6l1xcRBhGL+ai7W3YrBUmu2ccAS1gU0nAgwmKf3TXnxZRVCfYrNBcxqFtEO+0Ls0=
