language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- echo $AzureSqlServerPath
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: Mng9kDO8riVKiUpZn4xGY/80p1fMTU90aMrofGJ8EVJAsrjI5W5EjPLRMzQhMVrRcBwb+evd8pKHJA9M0QYhUU3rVTZdlkrhAdVHUfWaF8xzl31jy8OSE60sLWgrmaRJA+tLTm22XkVsxQSr/1S42bSPRAqX/XquZ5tw6w0K7RsI90PNr9MvZYgwdnlD7GWPBKnlQ6KYj5DHccGefv7atr0p43cCsXQOQ/jBxP8xd//xlMkMMXzWu8lUqEebQmvtHfiC0tmJWGByk+EW4qYyT1CMM/RFt/KwGaKA2ZLRMSQQ18hWEeJyU4v3pj1dP7KQA3sNlE/JpzOCAHqnIsq8B6l1qUvX85BnSKtBnhd1NcxhD4CFx/n3y6sqV/gSZzh/XAL4Qorv3RNzADGExJ3Gvd7+sZ3xrd3t7wR1/LTuxGL1sOeHcwsCdtcKe71aALe6UF8kG9HD/pBZMUU8wKUvz2qOQNWzScnkmq97j6f7JNmVp+2yAqrOuN9eyvVJG/f0ZcZHxoinWgZJ+F+9HOrNN8Rs72Npp3hkTDY9xxqAkmiHl3Z7O6MsIYXmQ2udNP6l3+6PZ6H3hyodahDt0kiFtVcAszdzTLNxpy9RB7be0rSZXrcri2qafqMG0oj47w9xIqdY2I1mdCBL4tRB539Ve1lABD+mwropfAGwRykbwyo=
