language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: Kyx0L3qVniVcQukeKJBTZI9yjKyM7iVmSZasNKZ2BuEB6VAvJ3uak+DL/s38mMP+4vj8M1cHCouKHUD9ZbgUjwJ4czEr53FLg5GyWXeeuF0O5b8knj03n3g3mCXpsRECnBb/CvIec42mPqfQ5ZAgBbUS4vg0+s+h7EB+xiWw/KsknniMzLp8heKRhI0u1M4LD3Kqmpeif2sAZnJjrcX4WOUlUIsX8BQBHU6Yn8zE0m93giAKV27kpxkQyXmuAdLa9TudybzmTikvvqOoBuIr9ruXKmiX5grv5T13DsiJNCBh1OwmIM/a5JCtePQFkEhGzZh1PhjSxAO1d/axTjKiXa/Vfw9WPAxDmDENN8wUYciOqePKDgxgcCDbTLykqMANG3isROZzdoXmynpx11/JItkI/DyC7TRy3GnF7xa+RtpTe9F2V0eby5ry0GUsuVLdNYxOb6QHLBoNqkAIsl0o6nmhrQCElU7LjuyHCvTUK3dCS78YNflMfIwRhgIKg7uRhvhhnJT3CoaGNhJS1+Rbbkou+KDo/ofvVPtJS6wrDMM8EdaTfHdbxE0a3/1Njy0rMDQwi5QH+e2T+saa2lRZjicqqNGsPCfM6DG+0kClkCxjo41vi61a19RI0ItO7Mwd4wK+V1DQRgm7g8H+lvdtJ0Duj0icC0jfyj1vZ0SYrSs=
