language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: DDtchFHSyxTxjYaOtzeG4AEUWEy1H+70qbmyTRRewPtkqDFhvWKfA6aFqjYsu72cf8f2f9B9EYd0JbWSQko7YSfC/PgNsy/NMlKPeQGHkrXggbqs1MNCi6rSbwy3Bf/CrhgACxbPt5hVoxlP/+/y56UQ+DKyoUTkJycmZys2pJGtpWHIF4Rmr2CLGZPRQfYVy0Mv/5HUUAeOOiG7bwnEDvo9WHwJ5bux2SHwMsCF6xGZCM97ppKZMjHfLjDpRwfSQ2JKkDz6egon6prWgDOpTCBjGlvXSxU9zTbRFfKNRwOwIgPk0OjIADaZBT98XmZjWS7WrRq4eFryQXrVZ/kbCUdxnx234Wj+IfETMlWELYTZ2ZTAYXucT1oSCVkoKZlBlVf6TOrlDCEEWxgA3H+wth9rmlHt21hShn7N3PRbYHlX8xR+1QBoZjBJ8O6ANJ49s2Ik15E04eKdSI0lW021CejhhFGJxnKzrT6p4Fuvu2nm763sQdL+ArqCno3p6PcW+2o1F1itS8mSR8pcElGktjNH/OIj1Dkn24ISqZUZKIYs+Y9vZJhnM2UdypwS3ABIniIj1+p8ry5RKp8HbzdBoQLYqrdD/0rJw0jQ+DjRwyLScVoi3+Eom4LoiVuAqAd7/2PeUEvoBoYWKw+PgCELL5CL6GLhsVmnY8axCMcj9+I=
