language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2
script:
- dotnet build -c Release
- dotnet test
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/SqlDatabaseBuilder/bin/Release/SqlDatabaseBuilder.*.nupkg
    --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
  - secure: BPhCLYI8eL7lk/7NQ0FG6z4o2Af9cpyE5zwLnFQSX0N/etURhhWqjsP7t1OCz5XxVv6vR1VLfcWnhwn3LL3HqbnbPp0wqllJuCQ9NZ80d66/2xVpmqvabhepZW8J/5zzxykC1dBAts5bpIZZb/P+gcnpsB3dxPWWmvY3maPQWv4KNkWzpCAh5fFc5Fg6I2WDg9E3GkD7TAalfMm/KWDPg6rx5XblQJwtNm0VmpkWPLVD7lBim++Z9pvEl0mh6qQEqnsUZJMdKP+TH7R3T8X3SlLGvnxq08PGYXu0cwrbh5Zo8iqDwZsX6lLmwbYo/S3gd2NxF75wxowSiDMoVC18iiQxSNpHyMYrOQ6N2HubNw8kt9HBR+2vsQ87nG0g5/8jxYCfhbir4T+jypudLtx/EeJxKssJeBRFWsVn52COlqvJjDpfZxHGeZyvs9akIDKJPo4//bpj0Gkx6xCUA0FQ4YUemA4Ql2dU6a8+gUF8wkH2Ajt8ZvHb7x58vDaEYw//uawKzfd1WAPg9safCimJ6TZJqhi0r2mS+8m/NsNIuWP5iMu8lQkTu1M2DmvuhVIv6xIsjBYgY8kw9MkRB5pAO4WgXU9NtS8PKZltahCRBcIQADDmvVQH1HPm58sefe48R3dZ6PRY3F8kRqVRc63CRH41t5nb2hOfLrPG6MbXwdU=
  - secure: qeBX/KDrGw6KBksHiZQlRQWOb+WLQBlhO5PE4fQ6UV7CSDm31xBV2Af5jvC9k6BnkE3OGR2tZNMED1FGiEKZtQw2uSOAZah2tjHFvERDr7TDDIKvZcdQRcDKdow2RDhoS/sVIHmxMeng/M42rR7AefaWC2zWafCkCuc99VSse06dL0O4yiUtNb5hTk/vUnp8rIcSeqZVDlB7/mkEyLb60c71qMNL32D0lFEmEESQ3NuLjJxHMaSSoYGwGF3DmRMAB9XiC6bFQdRqwGOWSXTt77WQ1oiAbbkje9hDBKROeAtfc7USLLeeW4g0rPWWdD5E0M1uCdnDFjDxVifFrZMhw4FfCV8827BuIp4XaOhhNO0iTtt7ZsCbV1Q1L/u1MlPtgjU2/5eqD0AwXoCCuYLziQ1z4eZ0drkxDPcJv0MFdlDLdQ+vAjoZMoB+URZXZ843yLZEhrB1n+r02fNUsT9Gq/Dn5usrRaNbO8+Gh4tcUK1bF0kvYiqIWVZdW/O7+cAzEtivk+UKvfPrszKfAfGOTizte6mxoyPx1oFA6/qTy9AouxvQNnJI4CzbTQwHW+HCdVPjqThvTZDvBoWuma+DkQ0E38edNOTglZZTyvjmwBi5SG3nP+TIi7YwKI6P3nzEm1HhRkrDJPGCDd5wliMWVT9XzVafXg962EUNethcs30=
